language: go

go:
  - 1.8.x
  - master

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -timeout 30s

after_success:
  - bash <(curl -s https://codecov.io/bash)