language: go

go:
  - 1.8.x
  - stable

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)